language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"
env:
  - TEST_TYPE=unit
  - TEST_TYPE=integration

jobs:
  include:
    - name: "Lint"
      python: "2.7"
      script: ./lint.sh all

before_install:
  - export FIREPIT=$HOME/.cache/firepit/firebase; [[ "$TEST_TYPE" != "integration" || -x "$FIREPIT" ]] || (curl -L https://github.com/abeisgoat/firebase-tools-release-playground/releases/download/v7.2.2/firebase-tools-headless-linux > "$FIREPIT" && chmod +x -- "$FIREPIT")
script:
  - if [[ "$TEST_TYPE" == "unit" ]]; then pytest; fi
  - if [[ "$TEST_TYPE" == "integration" ]]; then "$FIREPIT" emulators:exec --only database --project fake-project-id 'pytest integration/test_db.py'; fi
cache:
  pip: true
  npm: true
  directories:
  - $HOME/.cache/firebase/emulators
  - $HOME/.cache/firepit
